DROP TRIGGER IF EXISTS TRIGGER_INSERT_CONSOLIDATION on consolidation;

CREATE TRIGGER TRIGGER_INSERT_CONSOLIDATION
    AFTER INSERT ON consolidation
    FOR EACH ROW
    EXECUTE FUNCTION sp_insert_aggregation();