DROP TRIGGER IF EXISTS TRIGGER_UPDATE_CONSOLIDATION_PLACE on consolidation;

CREATE TRIGGER TRIGGER_UPDATE_CONSOLIDATION_PLACE
    AFTER UPDATE OF player_fold_round, player_winner ON consolidation
    FOR EACH ROW
    EXECUTE FUNCTION SP_UPDATE_AGGREGATION_PLACE();