DROP TRIGGER IF EXISTS TRIGGER_UPDATE_AGGREGATION_HANDS on aggregation;

CREATE TRIGGER TRIGGER_UPDATE_AGGREGATION_HANDS
    AFTER UPDATE OF qty_hands ON aggregation
    FOR EACH ROW
    EXECUTE FUNCTION SP_UPDATE_AGGREGATION_HANDS();