select * from tournaments;
select * from players;
select * from hands;
select * from board_of_hand;
select * from pot_of_hand;
select * from player_position;
select * from cards_of_player;
select * from blind_position;
select * from fold_position;