truncate table pokerline;
truncate table tournaments;
truncate table board_of_hand;
truncate table pot_of_hand;
truncate table cards_of_player;
truncate table blind_position;
truncate table fold_position;
truncate table win_position;
truncate table player_position cascade ;
truncate table players cascade;
truncate table hands cascade ;